author = ""
contact_form_action = "#"
description = "This is meta description"
logo = "images/luxury-real-estate-logo.jpg"
logo_width = "300px"
[navigation_button]
enable = true
label = "Get Started"
link = "contact"
[preloader]
enable = false
preloader = ""
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
[[social]]
icon = "fab fa-skype"
link = "#"
title = "skype"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
